### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by bbird1980** [mathertel/OneButton#8]
Using #include "OneButton.h" on my Arduino IDE 1.0.6 gives me error:

C:\Program Files (x86)\Arduino\libraries\OneButton/OneButton.h:59: error: ISO C++ forbids initialization of member '_debounceTicks'
C:\Program Files (x86)\Arduino\libraries\OneButton/OneButton.h:59: error: making '_debounceTicks' static

**Comment by mathertel** [comment]
You have 2 options: 
1. Please upgrade your project to the ARDUINO 1.6.5 version. The problem will disappear because the new compiler supports const class members.
2. remove the line 59 "const int _debounceTicks ..." in the OneButton.h file and define it as a global constant using a pre-compiler directive:
#define _debounceTicks 50
in OneButton.h before the class definition (line 25)...
